export const cards = [
  {
    id: 1,
    theme: "Other",
    title: "Сделать чай",
    date: "20.03.24",
    status: "Без статуса",
  },
  {
    id: 2,
    theme: "WebDesign",
    title: "Сделать макет сайта",
    date: "31.03.24",
    status: "Нужно сделать",
  },
  {
    id: 3,
    theme: "CopyWriting",
    title: "Написать статью",
    date: "10.03.24",
    status: "Готово",
  },
  {
    id: 4,
    theme: "Research",
    title: "Сделать домашку по React",
    date: "25.03.24",
    status: "В работе",
  },
  {
    id: 5,
    theme: "WebDesign",
    title: "Стилизовать компоненты",
    date: "30.03.24",
    status: "Тестирование",
  },
  {
    id: 6,
    theme: "Other",
    title: "Полы",
    date: "20.03.24",
    status: "Без статуса",
  },
  {
    id: 7,
    theme: "WebDesign",
    title: "Сделать макет сайта",
    date: "31.03.24",
    status: "Нужно сделать",
  },
  {
    id: 8,
    theme: "CopyWriting",
    title: "Написать статью",
    date: "10.03.24",
    status: "Готово",
  },
  {
    id: 9,
    theme: "Research",
    title: "Сделать домашку по React",
    date: "25.03.24",
    status: "В работе",
  },
  {
    id: 10,
    theme: "Other",
    title: "Стилизовать компоненты",
    date: "30.03.24",
    status: "Без статуса",
  },
];
